### ISSUE TITLE
Bug:icon display in wrong place 

### ISSUE THREAD

**Issue by zhongfly** [softvar/enhanced-github#78] opened 2020-12-25 11:08 UTC
chrome 87.0.4280.88
enhanced-github 5.0.4
some repo like:https://github.com/DIYgod/DPlayer/tree/gh-pages
1st flie don't show download icon but 2nd file icon link to 1st file,so on
![sample](https://user-images.githubusercontent.com/11155705/103133296-90c13100-46e4-11eb-923f-26b88d852950.png)
![sample2](https://user-images.githubusercontent.com/11155705/103134203-9457b680-46ea-11eb-9b4c-b2a3373aa488.png)

**Comment by zhongfly** [comment] 2020-12-25 11:46
also test in Edge 87.0.664.66 with https://github.com/softvar/enhanced-github/tree/gh-pages

**Comment by softvar** [comment] 2020-12-29 20:44
Thanks, @zhongfly for reporting this. This is now fixed in v5.0.5. Please update!

**Closed by softvar** 2020-12-29 20:44 UTC

**Comment by zhongfly** [comment] 2020-12-31 02:07
sorry to bother you，in some repo the bug happen again.
https://github.com/JustArchiNET/ArchiSteamFarm/tree/master
![Snipaste_2020-12-31_10-06-43](https://user-images.githubusercontent.com/11155705/103390540-e87df300-4b4f-11eb-8816-306e5ea8d543.png)

**Comment by softvar** [comment] 2021-01-02 07:19
Thanks again @softvar for reporting this. The issue is fixed in `v5.0.6`. Please update.
The issue was because of files that were treated as folders(size 0, pointing to other repositories.
